### ISSUE TITLE
Flow does not notify when data changes

### ISSUE THREAD

**Issue by raheemadamboev** [evilthreads669966/Pickpocket#4]
In my case, I'm using calendarFlow() and observing for calendar events.
If I insert new event from calendar, it does not notify new changes.

How can I solve it?

**Comment by evilthreads669966** [comment]
I'm not sure

**Comment by evilthreads669966** [comment]
Are you using two separate threads? I'm sorry. I forgot about this.

**Comment by evilthreads669966** [comment]
You might be better off using channels for now.

**Comment by evilthreads669966** [comment]
I don't think that you can flow off of a content provider. You can flow off of a room database table. It's not going to give you that,. You need a content observer. I'll make you a content observer library. Content Providers are a sqlite table as well. The proper way to do it is to query all from the content provider then you set a content observer on the same table and add new ones to your collection.

**Comment by evilthreads669966** [comment]
This is a content provider library as stated in the libraries description

**Comment by evilthreads669966** [comment]
Flowing from a content provider is more for using algorithms.

**Comment by evilthreads669966** [comment]
This isn't a bug.

**Comment by evilthreads669966** [comment]
So you would still use my library to do this. You use Pickpocket to get the current events and then you set a content observer on the database table.

**Comment by evilthreads669966** [comment]
also ContentObserver is best implemented as an inner class that has context that way you have access to the android context if you need it.
